### ISSUE TITLE
Powerpoint-style performance on mask-heavy map

### ISSUE THREAD

**Issue by Talanor** [caewok/fvtt-light-mask#20]
Hey Caewok,

First of all, thank you for the great module. I've been using it with great success on quite a few maps.

I'm having an issue now with a light (and masking from my end) heavy map.
I get that there might not be much to be done and I might just have to cut my losses and dial back the number of masks, but just in case you can find some optimization somewhere, I wanted to give you a scene JSON to play with.

[fvtt-Scene-light_sound-mask-powerpoint-j7ZPue50ZbLszv3X.json](https://github.com/user-attachments/files/17534849/fvtt-Scene-light_sound-mask-powerpoint-j7ZPue50ZbLszv3X.json)

Required modules for this to work should only be Light/Sound Mask and Wall-height, performance is restored by disabling Light/Sound Mask.
I use Foundry v12.331 on Chrome Version 129.0.6668.100 (Official Build) (64-bit)

Many thanks !

Edit : Deleting the masked lights barely improves the performance. The module lowers performance with a large number (115) of unmasked light as well.

**Comment by caewok** [comment]
Thanks for the scene json. I definitely can replicate the performance issue. Fixing it though is another story. I found a minor performance issue, but not the root cause. According to the Chrome performance analysis, nothing Light/Mask is doing directly is causing the issue. I suspect that something Light/Mask is doing is causing Foundry to re-initialize and re-render the light sources more than it should. Will keep looking.

**Comment by caewok** [comment]
Figured it out! It was rebuilding the edges even when the object in question—the token, in this case—didn't require a rebuild. v0.8.2 should be noticeably faster.
